name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: Risc-lt/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ waka_b064cb2b-a88f-4579-b1f4-997bc4c37cd0 }}
          GH_TOKEN: ${{ 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 }}
